version: '3'
services:
  webapp:
    build: webapp
    ports:
      - 3000:3000
  server:
    build: server
    ports:
      - 8080:8080
    networks:
      - backend
    environment:
      - MONGO_URL=mongodb://dashboard:SyA7Zr4cbcDwjD@mongo
    env_file:
    - "server/.env"
  mongo:
    image: mongo:5.0.4
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dashboard
      - MONGO_INITDB_ROOT_PASSWORD=SyA7Zr4cbcDwjD
networks:
  backend:
    driver: bridge
volumes:
  database: